version: "3.9"

services:
  backend:
    container_name: leetcode_reminders_backend
    build:
      context: backend
  frontend:
    container_name: leetcode_reminders_frontend
    build:
      context: frontend

networks:
  genesis_network:
    external: true